[package]
name = "storymaker"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0.185", features = ["derive"] }
serde-xml-rs = "0.6.0"
tokio = { version = "1.32.0", features = ["full"] }
