[package]
name = "storymaker"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
bevy = "0.11.2"
bevy_ecs_tilemap = "0.11.0"
tiled = "0.11.1"
tokio = { version = "1.32.0", features = ["full"] }
