[package]
name = "storymaker"
version = "0.0.1"
edition = "2021"

[dependencies]
bevy = "0.11"
bevy_ecs_tilemap = "0.11"
serde_json = "1.0.105"

[replace]
"bevy_ecs_tilemap:0.11.0" = { git = 'https://github.com/StarArawn/bevy_ecs_tilemap' }
