[package]
name = "storymaker_pathfinding"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nearest_path"
path = "src/nearest_path.rs"

[[bin]]
name = "find_path"
path = "src/find_path.rs"

[dependencies]
pathfinding = "4.3.1"
